<?php
use App\Sougi;
use Illuminate\Database\Seeder;

class SougiTableSeeder extends Seeder
{
    public function run()
    {
        for ($i = 1; $i <= 10; $i++) {
            Sougi::create([
                'reqYear' => "やっほほい" . $i,
                'reqMonth' => "やっほほい" . $i,
                'reqDay' => "やっほほい" . $i,
                'tuyaYear' => "やっほほい" . $i,
                'tuyaMonth' => "やっほほい" . $i,
                'tuyaDay' => "やっほほい" . $i,
                'tuyaHours' => "やっほほい" . $i,
                'tuyaMins' => "やっほほい" . $i,
                'tuyaHourf' => "やっほほい" . $i,
                'tuyaMinf' => "やっほほい" . $i,
                'tuyaHourg' => "やっほほい" . $i,
                'tuyaMing' => "やっほほい" . $i,
                'kokubetsuYear' => "やっほほい" . $i,
                'kokubetsuMonth' => "やっほほい" . $i,
                'kokubetsuDay' => "やっほほい" . $i,
                'kokubetsuHours' => "やっほほい" . $i,
                'kokubetsuMins' => "やっほほい" . $i,
                'kokubetsuHourf' => "やっほほい" . $i,
                'kokubetsuMinf' => "やっほほい" . $i,
                'kokubetsuHourg' => "やっほほい" . $i,
                'kokubetsuMing' => "やっほほい" . $i,
                'kasouYear' => "やっほほい" . $i,
                'kasouMonth' => "やっほほい" . $i,
                'kasouDay' => "やっほほい" . $i,
                'kasouHours' => "やっほほい" . $i,
                'kasouMins' => "やっほほい" . $i,
                'kasouHourf' => "やっほほい" . $i,
                'kasouMinf' => "やっほほい" . $i,
                'kasouHourg' => "やっほほい" . $i,
                'kasouMing' => "やっほほい" . $i,
                'soukaSpell'  => "やっほほい" . $i,
                'soukaName'  => "やっほほい" . $i,
                'kojinSpell'  => "やっほほい" . $i,
                'kojinName'  => "やっほほい" . $i,
                'kojinAddress'  => "やっほほい" . $i,
                'kojinHead'  => "やっほほい" . $i,
                'kojinPermAddress'  => "やっほほい" . $i,
                'kojinPrinciple'  => "やっほほい" . $i,
                'spouse'  => "やっほほい" . $i,
                'spouseAge'  => "やっほほい" . $i,
                'spouseStatus'  => "やっほほい" . $i,
                'kojinBirthYear'  => "やっほほい" . $i,
                'kojinBirthMonth'  => "やっほほい" . $i,
                'kojinBirthDay'  => "やっほほい" . $i,
                'kojinAge'  => "やっほほい" . $i,
                'kojinSex'  => "やっほほい" . $i,
                'deadYear'  => "やっほほい" . $i,
                'deadMonth'  => "やっほほい" . $i,
                'deadDay'  => "やっほほい" . $i,
                'deadHour'  => "やっほほい" . $i,
                'deadMin'  => "やっほほい" . $i,
                'moshuSpell'  => "やっほほい" . $i,
                'moshuName'  => "やっほほい" . $i,
                'moshuBirthYear'  => "やっほほい" . $i,
                'moshuBirthMonth'  => "やっほほい" . $i,
                'moshuBirthDay'  => "やっほほい" . $i,
                'moshuRelation'  => "やっほほい" . $i,
                'moshuMail'  => "やっほほい" . $i,
                'moshuTel1'  => "やっほほい" . $i,
                'moshuTel2'  => "やっほほい" . $i,
                'moshuAddress'  => "やっほほい" . $i,
                'moshuHead'  => "やっほほい" . $i,
                'moshuPermAddress'  => "やっほほい" . $i,
                'moshuPrinciple'  => "やっほほい" . $i,
                'repSpell'  => "やっほほい" . $i,
                'repName'  => "やっほほい" . $i,
                'repBirthYear'  => "やっほほい" . $i,
                'repBirthMonth'  => "やっほほい" . $i,
                'repBirthDay'  => "やっほほい" . $i,
                'repRelation'  => "やっほほい" . $i,
                'repTel1'  => "やっほほい" . $i,
                'repTel2'  => "やっほほい" . $i,
                'repAddress'  => "やっほほい" . $i,
                'repHead'  => "やっほほい" . $i,
                'repPermAddress'  => "やっほほい" . $i,
                'repPrinciple'  => "やっほほい" . $i,
                'demName'  => "やっほほい" . $i,
                'demTel'  => "やっほほい" . $i,
                'demAddress'  => "やっほほい" . $i,
                'payWay'  => "やっほほい" . $i,
                'employeeName' => "やっほほい" . $i,
                'compId' => "やっほほい" . $i,
                'cereId' => "やっほほい" . $i,
                'creId' => "やっほほい" . $i,
                'shuha' => "やっほほい" . $i,
                'ohuse' => "やっほほい" . $i,
                'returnItem' => "やっほほい" . $i,
                'specialArea' => "やっほほい" . $i,
            ]);
        }
    }
}
