<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sougi extends Model
{
    protected $fillable =[
        'reqYear',
        'reqMonth',
        'reqDay',
        'tuyaYear',
        'tuyaMonth',
        'tuyaDay',
        'tuyaHours',
        'tuyaMins',
        'tuyaHourf',
        'tuyaMinf',
        'tuyaHourg',
        'tuyaMing',
        'kokubetsuYear',
        'kokubetsuMonth',
        'kokubetsuDay',
        'kokubetsuHours',
        'kokubetsuMins',
        'kokubetsuHourf',
        'kokubetsuMinf',
        'kokubetsuHourg',
        'kokubetsuMing',
        'kasouYear',
        'kasouMonth',
        'kasouDay',
        'kasouHours',
        'kasouMins',
        'kasouHourf',
        'kasouMinf',
        'kasouHourg',
        'kasouMing',
        'soukaSpell' ,
        'soukaName' ,
        'kojinSpell' ,
        'kojinName' ,
        'kojinAddress' ,
        'kojinHead' ,
        'kojinPermAddress' ,
        'kojinPrinciple' ,
        'spouse' ,
        'spouseAge' ,
        'spouseStatus' ,
        'kojinBirthYear' ,
        'kojinBirthMonth' ,
        'kojinBirthDay' ,
        'kojinAge' ,
        'kojinSex' ,
        'deadYear' ,
        'deadMonth' ,
        'deadDay' ,
        'deadHour' ,
        'deadMin' ,
        'moshuSpell' ,
        'moshuName' ,
        'moshuBirthYear' ,
        'moshuBirthMonth' ,
        'moshuBirthDay' ,
        'moshuRelation' ,
        'moshuTel1' ,
        'moshuTel2' ,
        'moshuAddress' ,
        'moshuHead' ,
        'moshuPermAddress' ,
        'moshuPrinciple' ,
        'repSpell' ,
        'repName' ,
        'repBirthYear' ,
        'repBirthMonth' ,
        'repBirthDay' ,
        'repRelation' ,
        'repTel1' ,
        'repTel2' ,
        'repAddress' ,
        'repHead' ,
        'repPermAddress' ,
        'repPrinciple' ,
        'demName' ,
        'demTel' ,
        'demAddress' ,
        'payWay' ,
        'employeeName',
        'compId',
        'cereId',
        'creId',
        'shuha',
        'ohuse',
        'returnItem',
        'specialArea',
    ];
}
